config/routes.rb
Ideias::Application.routes.draw do
  resources :events do
    resources :ideas do
      resources :authors
    end
  end

  root :to => 'events#index'

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  attr_accessible :descricao, :keywords, :link, :nome, :repositorio

  belongs_to :event
  has_many :authors
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  # GET /ideas
  # GET /ideas.json
  def index
    @event = Event.find params[:event_id]
    @ideas = @event.ideas

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ideas }
    end
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @event = Event.find params[:event_id]
    @idea = Idea.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/new
  # GET /ideas/new.json
  def new
    @event = Event.find params[:event_id]
    @idea = Idea.new
    @idea.event = @event

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/1/edit
  def edit
    @idea = Idea.find(params[:id])
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @event = Event.find params[:event_id]
    @idea = Idea.new(params[:idea])
    @idea.event = @event

    respond_to do |format|
      if @idea.save
        format.html { redirect_to [@event,@idea], notice: 'Idea was successfully created.' }
        format.json { render json: @idea, status: :created, location: @idea }
      else
        format.html { render action: "new" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ideas/1
  # PUT /ideas/1.json
  def update
    @idea = Idea.find(params[:id])

    respond_to do |format|
      if @idea.update_attributes(params[:idea])
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy

    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_authors.html.erb
<h3>Autoras</h3>

<ul>
<% @idea.authors.each do |author| %>
  <li>
    <p><%= link_to author.nome, event_idea_author_path(@event,@idea,author) %></p>
  </li>
<% end %>
</ul>

<br />

app/views/ideas/_form.html.erb
<%= form_for [@event,@idea] do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :keywords %><br />
    <%= f.text_field :keywords %>
  </div>
  <div class="field">
    <%= f.label :repositorio %><br />
    <%= f.text_field :repositorio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', [@event, @idea] %> |
<%= link_to 'Back', event_ideas_path %>

app/views/ideas/index.html.erb
<div class="container">
<h1>Ideias do evento <%= @event.name %></h1>


<ul class="ideas">
	<li class="idea">
		<%= link_to 'New Idea', new_event_idea_path %>
	</li>
<% @ideas.each do |idea| %>
  	<li class="idea">
  		<div align="center">
    	<h3><%= link_to idea.nome, event_idea_path(@event, idea) %></h3>
    </div>
    	<br />
    	Authors:
    	<%= idea.authors.map {|a| a.nome}.join ',' %>
    	<p><%= idea.link %></p>
    	<p><%= link_to 'Edit', edit_event_idea_path(@event, idea) %></p>
	</li>
<% end %>
</ul>

<br />
</div>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', event_ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @idea.nome %>
</p>

<p>
  <b>Descricao:</b>
  <%= @idea.descricao %>
</p>

<p>
  <b>Link:</b>
  <%= @idea.link %>
</p>

<p>
  <b>Keywords:</b>
  <%= @idea.keywords %>
</p>

<p>
  <b>Repositorio:</b>
  <%= @idea.repositorio %>
</p>


<%= render 'authors' %>

<%= link_to 'Add Author', new_event_idea_author_path(@event,@idea)%>
<br/>
<br/>
<%= link_to 'Back', events_path %>