config/routes.rb
Ideias::Application.routes.draw do
  resources :events do
    resources :ideas do
      resources :authors
    end
  end

  root :to => 'events#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :bio, :link, :nivel, :nome, :sexo, :email

  validates_presence_of :nome
  validates_inclusion_of :sexo, in: ['female', 'male']
  validates_format_of :nome, with: /^[a-zA-Z]+$/



  belongs_to :idea
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @event = Event.find params[:event_id]
    @idea = Idea.find params[:idea_id]
    @author = Author.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.json
  def new
    @event = Event.find params[:event_id]
    @idea = Idea.find params[:idea_id]
    @author = Author.new
    @author.idea = @idea

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/1/edit
  def edit
    @event = Event.find params[:event_id]
    @idea = Idea.find params[:idea_id]
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.json
 def create
    @event = Event.find params[:event_id]
    @idea = Idea.find params[:idea_id]
    @author = Author.new(params[:author])
    @author.idea = @idea

    @event = Event.find params[:event_id]
    @idea = Idea.find params[:idea_id]

    respond_to do |format|
      if @author.save
        format.html { redirect_to [@event,@idea], notice: 'Author was successfully created.' }
        format.json { render json: @author, status: :created, location: @author }
      else
        format.html { render action: "new" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.json
 def update
    @event = Event.find params[:event_id]
    @idea = Idea.find params[:idea_id]
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to [@event,@idea], notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_for([@event,@idea,@author]) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :sexo %><br />
    <%= f.text_field :sexo %>
  </div>

  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :nivel %><br />
    <%= f.text_field :nivel %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Back', event_idea_authors_path %>

app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Link</th>
    <th>Nivel</th>
    <th>Bio</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authors.each do |author| %>
  <tr>
    <td><%= author.nome %></td>
    <td><%= author.link %></td>
    <td><%= author.nivel %></td>
    <td><%= author.bio %></td>
    <td><%= link_to 'Show', author %></td>
    <td><%= link_to 'Edit', edit_author_path(author) %></td>
    <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', event_idea_authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @author.nome %>
</p>

<p>
  <b>Link:</b>
  <%= @author.link %>
</p>

<p>
  <b>Nivel:</b>
  <%= @author.nivel %>
</p>

<p>
  <b>Bio:</b>
  <%= @author.bio %>
</p>