config/routes.rb
Ideias::Application.routes.draw do
  resources :events do
    resources :ideas do
      resources :authors
    end
  end

  root :to => 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :name, :city, :country, :data

  has_many :ideas
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.date_select :data %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_ideas.html.erb
<div class="container">
<h3>Ideias do evento <%= @event.name %></h3>


<ul class="ideas">
	<li class="idea">
		<%= link_to 'New Idea', new_event_idea_path(@event) %>
	</li>
<% @event.ideas.each do |idea| %>
  	<li class="idea">
  		<div align="center">
    	  <h3><%= link_to idea.nome, event_idea_path(@event, idea) %></h3>
      </div>
    	<br />
    	Authors:
    	<%= idea.authors.map {|a| a.nome}.join ',' %>
    	<p><%= idea.link %></p>

	</li>
<% end %>
</ul>

<br />
</div>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Eventos Rails Girls</h1>


<ul class="ideas">
  <li class="idea">
    <%= link_to 'New Event', new_event_path %>
  </li>
<% @events.each do |event| %>
    <li class="idea">
      <div align="center">
      <h3><%= link_to event.name, event %></h3>
    </div>
      <br />
      <p><%= event.city %></p>
      <p><%= event.country %></p>
      <%= link_to 'Edit', edit_event_path(event) %>
      <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Deletar o evento. Sério?' } %>
  </li>
<% end %>
</ul>

<br />

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>City:</b>
  <%= @event.city %>
</p>

<p>
  <b>Data:</b>
  <%= @event.data %>
</p>

<p>
  <b>Country:</b>
  <%= @event.country %>
</p>
<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

<%= render 'ideas' %>